### ISSUE TITLE
Add —write-metadata

### ISSUE THREAD

**Issue by upintheairsheep** [NyaMisty/ipatool-py#14]
Add a flag that writes metadata:
1. Screenshots for all platforms and reviews in their original format. as (ipa name).screenshot-(number).(format) and a single (ipa name).screenshot-info.json with the original URLs of the screenshots and the platforms their on as well as links to the videos.
2. Reviews as a (ipa name).reviews.json with the review content, star rating, age, and title.  If an app has more than 1000 reviews you need to use the —write-all-reviews to write all of them.
3. Icon as a (ipa name).icon.(file format)
4. Description as a (ipa name).description.txt
5. Version history as a .versionhistory.json with number, date, and developer description with bullets
6. Privacy information about the app gets written to .privacypolicy.json
7. Miscellaneous fields like app size, category, developer name, developer ID, ratings without a review, etc go to .info.json .

**Comment by NyaMisty** [comment]
Metadata was now preserved inside IPAToolInfo.plist
