### ISSUE TITLE
Apps without Manifest.plist results in crash

### ISSUE THREAD

**Issue by minif** [NyaMisty/ipatool-py#17]
First, I would like to mention that I am using the action-iTunes-header method in a VM, in case this is important.

Lots of (older) apps do not have a Manifest.plist file in SC_Info. One example of such an app I have chosen is [this app](https://apps.apple.com/us/app/tic-tacky-to/id379485289). The tool assumes the file always exists and uses it to get the names of .sinf files. Because of this, the program crashes with the following message when downloading these apps:
`KeyError: "There is no item named 'Payload/tic-tac-toe.app/SC_Info/Manifest.plist' in the archive"`

On line 298: 
`scManifestData = ipaFile.read(appContentDir + '/SC_Info/Manifest.plist')`

Some form of check would need to be put in place to ensure Manifest.plist exists, and if it does not use a different method to obtain .sinf files. I _think_ that `CFBundleExecutable` from info.plist is the name for the .sinf, but I would need to perform more research or testing to confirm this.

**Comment by NyaMisty** [comment]
Fixed. Sorry for the latency :(
