### ISSUE TITLE
License not found exception handing broken

### ISSUE THREAD

**Issue by z-tux-mind** [NyaMisty/ipatool-py#23]
Hi, first of all, thank you for this great tool!

I think that there has been a regression between 1f4d9b06bedbf902d6359acb9c609f6ec25d0ab8 and a8b2d37bba40ed427420f6a2a8fa9a89c4844256 ( [compare] ).

When downloading without the new `--purchase` option a not previously purchased item, the exception handling itself fails.

In particular, the change from

```py
raise StoreException("download", resp.customerMessage, resp.failureType)
```

to

```py
raise StoreException("volumeStoreDownloadProduct", resp, resp.customerMessage, resp.failureType + '-' + resp.metrics.dialogId)
```

Seems to be the cause.

When debugging with `pdb`, I can inspct the `resp` object, which seems to have a its `metrics` field set to `None`:

```
<Class StoreDownloadResp. pings: [], cancel_purchase_batch: True, customerMessage: 'License not found', failureType: '9610', jingleDocType: None, jingleAction: None, status: None, dsPersonId: None, creditDisplay: None, creditBalance: None, freeSongBalance: None, authorized: None, download_queue_item_count: None, songList: None, metrics: None, subscriptionStatus: None>
```

Once again, thank you for this great and useful tool and for adding the purchase option!
All the best, tuxmind.

[compare]: https://github.com/NyaMisty/ipatool-py/compare/1f4d9b06bedbf902d6359acb9c609f6ec25d0ab8...a8b2d37bba40ed427420f6a2a8fa9a89c4844256

**Comment by NyaMisty** [comment]
I've rewritten the handling logic, so I can't merge your PR, sorry & thanks!
