### ISSUE TITLE
Unable to purchase an app + Readme issue

### ISSUE THREAD

**Issue by ZonD80** [NyaMisty/ipatool-py#26]
Getting MZCommerce.PriceMismatch error - so unable to purchase paid apps

Also you need to mention in readme that user needs to authorise computer and make first purchase in iTunes with marked "do not ask for password" checkbox, otherwise this error throws: MZCommerce.ConfirmationNeededForOneClickBuy.SoftwareApplication, it is not handled in your code.

**Comment by ipatch** [comment]
> Getting MZCommerce.PriceMismatch error - so unable to purchase paid apps
> 
> Also you need to mention in readme that user needs to authorise computer and make first purchase in iTunes with marked "do not ask for password" checkbox, otherwise this error throws: MZCommerce.ConfirmationNeededForOneClickBuy.SoftwareApplication, it is not handled in your code.

gold, i kept getting an error response code until i authorized my computer with itunes installed.

**Comment by NyaMisty** [comment]
Added a readme notice :)
Thank you!
