### ISSUE TITLE
A project that can download the old version without kbsync

### ISSUE THREAD

**Issue by KleinerSource** [NyaMisty/ipatool-py#49]
https://github.com/wf021325/ipatool.js
You can refer to it.

**Comment by minif** [comment]
Looking into this, it looks like `externalVersionID` is a key that you need include in the request you make to the volumeStoreDownloadProduct api (the one that uses Apple ID auth). So a request is something like 

```‹dict>
‹key>creditDisplay</key>
<string></string>
‹key>guid</key>
<string></string>
<key>salableAdamId</key>
<string>653726467</string>
‹key>externalVersionId</key> <string>15473547</string>
</dict>```

Which should be super easy to implement
