### ISSUE TITLE
Automatically obtain license

### ISSUE THREAD

**Issue by rehmatworks** [NyaMisty/ipatool-py#5]
Is this possible that this script automatically obtains a license by simulating the purchase? For free apps only. If you can add that feature, that'd be super cool. Thank you so much for your great contribution.

**Comment by NyaMisty** [comment]
If Apple Configurator can, then I can, if it cannot, then I cannot achieve it either.
And I don't own a Mac, please tell me the which one is the real case and I'll give it a try ;)

**Comment by rehmatworks** [comment]
Thank you for you replying :) I can analyze the code and I can let you know more if I succeed in finding details. I have tried using Charles proxy but looks like the Apple Store Mac app is using SSL pinning and I am not getting it to work. If I succeed, I'll be able to contribute to this project.

**Comment by vadimszzz** [comment]
>If Apple Configurator can, then I can, if it cannot, then I cannot achieve it either.
No you're wrong ;)
Take a look at this please
https://github.com/gergul/xhASOios/blob/996956aca9/xhiTunes/xhiTunes.cpp#L2805
https://github.com/gergul/xhASOios/blob/996956aca9ad8b49a0fb03826466eb69ff237bb7/xhwork/xhwork.cpp#L5288
https://github.com/gergul/xhASOios/blob/996956aca9ad8b49a0fb03826466eb69ff237bb7/xhwork/viewpage.cpp#L9924

**Comment by NyaMisty** [comment]
You think I don't know those iTunes hook guys?

"Take a look at my AutoIPADownload please"

I don't want to have any Windows iTunes dependencies.

**Comment by vadimszzz** [comment]
What? It doesnt need windows, it's depends on iTunes.dll but they have their own xhiTunes.cpp independent implementation which can be rewrote in python.

**Comment by vadimszzz** [comment]
> DLL application.

Oh sorry it's dependent library.
I'll do some reverse-engineering research to achieve absolutely independent algorithm without iTunes. It's very hard work.

**Comment by NyaMisty** [comment]
In short: you can't
As no one really successfully reverse engineered the FairPlay

FIRST_NAME LAST_NAME ***@***.***> 于2021年11月11日周四 下午10:47写道：

**Comment by DarielHG89** [comment]
hi, any news obtaining the app license?

**Comment by langkhach270389** [comment]
ipatool release support obtain license. Please update features. Thanks

To obtain a license for an app, use the purchase command.

OVERVIEW: Obtain a license for the app from the App Store.

USAGE: ipatool purchase --bundle-ide

**Comment by R1p4eg** [comment]
+1 for this feature from ipatool. 

Thank you!

**Comment by NyaMisty** [comment]
Now it have this feature, thanks for letting me know!

**Comment by vadimszzz** [comment]
> In short: you can't As no one really successfully reverse engineered the FairPlay FIRST_NAME LAST_NAME ***@***.***> 于2021年11月11日周四 下午10:47写道：
> […](#)

Their algorithm is not obfuscated or something. Looks like just nobody have tried.

**Comment by vadimszzz** [comment]
> ipatool release support obtain license. Please update features. Thanks
> 
> To obtain a license for an app, use the purchase command.
> 
> OVERVIEW: Obtain a license for the app from the App Store.
> 
> USAGE: ipatool purchase --bundle-ide

Wow, I thought it would never happen if I wouldn’t do that 
Very nice
