### ISSUE TITLE
Can't sign in, 2FA code gets recognized as a separate event?

### ISSUE THREAD

**Issue by MWRevamped** [NyaMisty/ipatool-py#54]
python3 main.py download -i 333903271 -e user@gmail.com -p password!309667
zsh: no such event: 309667

**Comment by MWRevamped** [comment]
could it be because of the exclamation mark inside the password?

**Comment by MWRevamped** [comment]
it was the exclamation, turns out zsh uses it for history expansion, if anyone else is having this issue on Mac use 

setopt nobanghist

in terminal to get rid of this stupid thing.

**Comment by davipt** [comment]
Always wrap strings with quotes. Typically double quotes are enough, unless they include variables ($), or stuff, and exclamation points. Single quotes solves that.
