### ISSUE TITLE
2fa

### ISSUE THREAD

**Issue by yadude87** [NyaMisty/ipatool-py#6]
i cant use 2fa needs code

**Comment by MissThee** [comment]
> i cant use 2fa needs code
try using `download` command twice with 2FA code

1.  Use `download` command with your account and password
```
python main.py download -i 123456 -e xxxxxxx@xx.xx -p xxxxxxxxx
```
2.  Now you should receive the 2FA code. Use `download` command with your account and password+2FA code
```
python main.py download -i 123456 -e xxxxxxx@xx.xx -p xxxxxxxxx212121
```
Now you should be able to login and download correctly 

idea from [majd/ipatool: Unable to login with 2FA](https://github.com/majd/ipatool/issues/30#issuecomment-962301006)
